version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - .//webs:/var/www
      - .//data/nginx/conf.d:/etc/nginx/conf.d
      - .//data/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

    networks:
      default:
        aliases:
          - osmand.localhost
